-- 016_manager_hierarchy.sql
-- DEPRECATED: Originally added manager_id column.
-- manager_id was removed in favor of the existing reports_to column.
-- This migration is kept for history only — the column no longer exists.
-- The reporting hierarchy now uses employees.reports_to exclusively.
